##### The original data file 'Li et al. OA viscosity_Table S2.xls' distributed under Creative Commons Attribution 4.0 International license was exported in Microsoft Excel to 'li_1.csv' and 'li_2.csv' files.

##### This file preprocesses the 'li_1.csv' and 'li_2.csv' files. The content of this file acts as the documentation of modifications and adaptations that are required to be indicated and marked according to the license
###### More information: https://wiki.creativecommons.org/wiki/License_Versions#Modifications_and_adaptations_must_be_marked_as_such

In [ ]:
import pandas as pd
import cirpy as c
import numpy as np

In [ ]:
# Load first data file (CAS)
data = pd.read_csv('li_1.csv')
data['CAS'] = data['CAS'].apply(lambda x: x.lstrip('0')) # Remove leading zeros from CAS-numbers
data.head(5)

,Unnamed: 0,CAS,#C,#H,#N,#O,#S,Molar mass (g/mol),Measured C0 (μg/m3),Estimated C0 (μg/m3),Measured Tm (K),Estimated Tm (K),Estimated Tg (K)
0,0,50-00-0,1,2,0,1,0,"30,026",6273582438,5634277589,"181,15",NaN,"126,805"
1,1,50-21-5,3,6,0,3,0,"90,079","393753,6687","138516,0507","289,95",NaN,"202,965"
2,2,50-32-8,20,12,0,0,0,"252,32","0,074449956","0,013316914","449,65",NaN,"314,755"
3,3,50-36-2,17,21,1,4,0,"303,36","3,114350973","210,340982","371,15",NaN,"259,805"
4,4,50-78-2,9,8,0,4,0,"180,16","244,0982153","635,4302748","408,15",NaN,"285,705"

In [ ]:
# Convert CAS-numbers to SMILES strings using cirpy CAS resolver
cas_vals = data['CAS'].values
smiles = []
for cas in cas_vals:
    try:
        smiles.append(c.resolve(cas, 'smiles'))
    except:
        print('Error')

smiles = np.array(smiles)
data['SMILES'] = smiles

In [ ]:
data = data.drop(columns=['CAS']) # Remove unnecessary column
# Load second data file
data2 = pd.read_csv('li_2.csv')

In [ ]:
# Concatenate both data file contents to one dataframe
data_all = pd.concat([data, data2])

In [7]:
data_all.values.shape
print(len(smiles[smiles == None]))

20

In [8]:
data_all.to_csv('li_all.csv')

In [ ]:
# Prune unresolved data entries
data_no_nones = data[smiles != None]
tg = data_no_nones['Estimated Tg (K)'].values
data_no_nones = data_no_nones[tg != None]

In [10]:
data_all_smiles = pd.concat([data_no_nones, data2])
data_all_smiles.to_csv('li_all_smiles.csv')

In [ ]:
# Save smiles strings
with open('smiles.txt', 'w+') as file:
    for smi in data_all_smiles['SMILES'].values:
        file.writelines(smi + '\n')

In [12]:
data_smiles = pd.read_csv('li_all_smiles.csv')
data_smiles.head(10)

,Unnamed: 0.1,Unnamed: 0,#C,#H,#N,#O,#S,Molar mass (g/mol),Measured C0 (μg/m3),Estimated C0 (μg/m3),Measured Tm (K),Estimated Tm (K),Estimated Tg (K),SMILES
0,0,0,1,2,0,1,0,"30,026",6273582438,5634277589,"181,15",NaN,"126,805",C=O
1,1,1,3,6,0,3,0,"90,079","393753,6687","138516,0507","289,95",NaN,"202,965",CC(O)C(O)=O
2,2,2,20,12,0,0,0,"252,32","0,074449956","0,013316914","449,65",NaN,"314,755",c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
3,4,4,9,8,0,4,0,"180,16","244,0982153","635,4302748","408,15",NaN,"285,705",CC(=O)Oc1ccccc1C(O)=O
4,5,5,6,4,2,5,0,"184,11","3861,659597","127,7318174","388,65",NaN,"272,055",Oc1ccc(cc1[N+]([O-])=O)[N+]([O-])=O
5,6,6,3,7,1,2,0,"89,095","1255303,055","1987603,083","322,15",NaN,"225,505",CCOC(N)=O
6,7,7,22,44,0,0,0,"278,36","0,015828715","0,000230387","542,65",NaN,"379,855",c1ccc2c(c1)ccc3cc4c(ccc5ccccc45)cc23
7,8,8,10,14,2,0,0,"162,24","331276,1493","278969,3889","194,15",NaN,"135,905",CN1CCC[C@H]1c2cccnc2
8,9,9,4,10,2,1,0,"102,14","4720523,688","8398140,979",NaN,NaN,NaN,CCN(CC)N=O
9,10,10,3,5,3,9,0,"227,09","4886,269389","332266,3185","286,65",NaN,"200,655",[O-][N+](=O)OCC(CO[N+]([O-])=O)O[N+]([O-])=O

In [13]:
data_smiles = data_smiles.dropna(subset=['Estimated Tg (K)'])
data_smiles.head(10)

,Unnamed: 0.1,Unnamed: 0,#C,#H,#N,#O,#S,Molar mass (g/mol),Measured C0 (μg/m3),Estimated C0 (μg/m3),Measured Tm (K),Estimated Tm (K),Estimated Tg (K),SMILES
0,0,0,1,2,0,1,0,"30,026",6273582438,5634277589,"181,15",NaN,"126,805",C=O
1,1,1,3,6,0,3,0,"90,079","393753,6687","138516,0507","289,95",NaN,"202,965",CC(O)C(O)=O
2,2,2,20,12,0,0,0,"252,32","0,074449956","0,013316914","449,65",NaN,"314,755",c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
3,4,4,9,8,0,4,0,"180,16","244,0982153","635,4302748","408,15",NaN,"285,705",CC(=O)Oc1ccccc1C(O)=O
4,5,5,6,4,2,5,0,"184,11","3861,659597","127,7318174","388,65",NaN,"272,055",Oc1ccc(cc1[N+]([O-])=O)[N+]([O-])=O
5,6,6,3,7,1,2,0,"89,095","1255303,055","1987603,083","322,15",NaN,"225,505",CCOC(N)=O
6,7,7,22,44,0,0,0,"278,36","0,015828715","0,000230387","542,65",NaN,"379,855",c1ccc2c(c1)ccc3cc4c(ccc5ccccc45)cc23
7,8,8,10,14,2,0,0,"162,24","331276,1493","278969,3889","194,15",NaN,"135,905",CN1CCC[C@H]1c2cccnc2
9,10,10,3,5,3,9,0,"227,09","4886,269389","332266,3185","286,65",NaN,"200,655",[O-][N+](=O)OCC(CO[N+]([O-])=O)O[N+]([O-])=O
10,11,11,21,16,0,0,0,"268,36","0,62014723","0,337475469","453,15",NaN,"317,205",Cc1ccc2cc3c(ccc4ccccc34)c5CCc1c25

In [ ]:
try:
    data_smiles = data_smiles.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
    data_smiles.to_csv('li_all_smiles_cleaned.csv')
except:
    print('Something went wrong')
# Save smiles strings
with open('smiles.txt', 'w+') as file:
    for smi in data_smiles['SMILES'].values:
        file.writelines(smi + '\n')
# Save tg values
with open('tg.txt', 'w+') as file:
    for tg in data_smiles['Estimated Tg (K)'].values:
        file.writelines(
            tg.replace(',', '.') + '\n'
            )

In [ ]:
data_smiles = pd.read_csv('li_all_smiles.csv')
data_smiles = data_smiles.dropna(subset=['Estimated Tg (K)'])

,Unnamed: 0.1,Unnamed: 0,#C,#H,#N,#O,#S,Molar mass (g/mol),Measured C0 (μg/m3),Estimated C0 (μg/m3),Measured Tm (K),Estimated Tm (K),Estimated Tg (K),SMILES
0,0,0,1,2,0,1,0,"30,026",6273582438,5634277589,"181,15",NaN,"126,805",C=O
1,1,1,3,6,0,3,0,"90,079","393753,6687","138516,0507","289,95",NaN,"202,965",CC(O)C(O)=O
2,2,2,20,12,0,0,0,"252,32","0,074449956","0,013316914","449,65",NaN,"314,755",c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
3,4,4,9,8,0,4,0,"180,16","244,0982153","635,4302748","408,15",NaN,"285,705",CC(=O)Oc1ccccc1C(O)=O
4,5,5,6,4,2,5,0,"184,11","3861,659597","127,7318174","388,65",NaN,"272,055",Oc1ccc(cc1[N+]([O-])=O)[N+]([O-])=O
5,6,6,3,7,1,2,0,"89,095","1255303,055","1987603,083","322,15",NaN,"225,505",CCOC(N)=O
6,7,7,22,44,0,0,0,"278,36","0,015828715","0,000230387","542,65",NaN,"379,855",c1ccc2c(c1)ccc3cc4c(ccc5ccccc45)cc23
7,8,8,10,14,2,0,0,"162,24","331276,1493","278969,3889","194,15",NaN,"135,905",CN1CCC[C@H]1c2cccnc2
9,10,10,3,5,3,9,0,"227,09","4886,269389","332266,3185","286,65",NaN,"200,655",[O-][N+](=O)OCC(CO[N+]([O-])=O)O[N+]([O-])=O
10,11,11,21,16,0,0,0,"268,36","0,62014723","0,337475469","453,15",NaN,"317,205",Cc1ccc2cc3c(ccc4ccccc34)c5CCc1c25

### Summary of modifications and adaptations:
#### - Convert CAS-numbers to SMILES strings for data entries in li_1.csv
#### - Save columns: 'SMILES', 'Estimated Tg (K)' to files of different format 'smiles.txt', 'tg.txt' without headers
#### - Save intermediate results to 'li_all.csv', 'li_all_smiles.csv', 'li_all_smiles_cleaned.csv'